import enum

class ItemStatus(enum.Enum):
    NEW_REQUEST = "NEW REQUEST"  # This matches what's in your database
    PENDING_APPROVAL = "PENDING APPROVAL"  # Added to match frontend expectations
    APPROVED = "APPROVED"
    DENIED = "DENIED"
    ON_HOLD = "ON HOLD"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"

class TaskStatus(enum.Enum):
    NEW_REQUEST = "NEW REQUEST"
    PENDING     = "PENDING"
    PROCESSED   = "PROCESSED"
    ERROR       = "ERROR"
    CANCELLED   = "CANCELLED" 
    
class PRProgress(enum.Enum):
    ID_GENERATED = "ID_GENERATED"
    PR_HEADERS_INSERTED = "PR_HEADERS_INSERTED"
    LINE_ITEMS_INSERTED = "LINE ITEMS INSERTED"
    GENERATE_PDF = "GENERATE_PDF"
    PDF_GENERATED = "PDF_GENERATED"
    SEND_APPROVER_EMAIL = "SEND_APPROVER_EMAIL"
    SEND_REQUESTER_EMAIL = "SEND_REQUESTER_EMAIL"
    EMAIL_SENT_REQUESTER = "EMAIL_SENT_REQUESTER"
    EMAIL_SENT_APPROVER = "EMAIL_SENT_APPROVER"
    PENDING_APPROVAL_INSERTED = "PENDING_APPROVAL_INSERTED"