---
prod_or_dev:
    prod: false
    dev: true

api_url:
    dev: http://${HOSTNAME}:5002
    prod: https://${HOSTNAME}:5004

api_routes:
    login: /api/login
    approval: /api/getApprovalData
    purchase: /api/sendToPurchaseReq
